<?php

$data = <<<EOL
{
    "1": [
        "Spurs",
        "Casey Kasem",
        "France vs Honduras",
        "Fathers Day",
        "Martin Kaymer",
        "Father's Day",
        "Gregg Popovich",
        "Lady Stoneheart",
        "Messi",
        "England vs Italy",
        "Happy Fathers Day",
        "Switzerland vs Ecuador",
        "Fathers Day Quotes",
        "Martin Kaymer",
        "Flag Day",
        "Jason Momoa",
        "LA Kings",
        "Ivory Coast",
        "Uruguay vs Costa Rica",
        "Friday the 13th"
    ],
    "3": [
        "Michael Schumacher",
        "Live Score",
        "Argentina Vs Bosnia And Herzegovina",
        "Kick",
        "France vs Honduras",
        "Father's Day 2014",
        "cricket",
        "Switzerland vs Ecuador",
        "Côte D'ivoire Vs Japan",
        "Germany vs Portugal",
        "Happy Father Day",
        "Bhutan",
        "Fathers Day",
        "Uruguay vs Costa Rica",
        "Fathers Day Quotes",
        "England vs Italy",
        "Ness Wadia",
        "Chile vs Australia",
        "Colombia vs Greece",
        "Maksim Chmerkovskiy"
    ],
    "4": [
        "武田梨奈",
        "ヨックモック",
        "アルゼンチン",
        "園子温",
        "飯豊まりえ",
        "ワールドカップ",
        "サッカー",
        "コートジボワール",
        "ドログバ",
        "サッカー日本代表",
        "地震",
        "本田圭佑",
        "イングランド",
        "コスタリカ",
        "サッカー ワールドカップ",
        "日本",
        "コロンビア",
        "ヤヤトゥーレ",
        "でんぱ組",
        "バロテッリ"
    ],
    "5": [
        "Kawhi Leonard",
        "Michael Schumacher",
        "Casey Kasem",
        "Vermaelen",
        "Iran vs Nigeria",
        "England vs Italy",
        "Argentina Vs Bosnia And Herzegovina",
        "Switzerland vs Ecuador",
        "France vs Honduras",
        "Germany vs Portugal",
        "Fathers Day",
        "Van Persie",
        "England vs Italy",
        "Côte D'ivoire Vs Japan",
        "Father Day 2014",
        "Uruguay vs Costa Rica",
        "Colombia vs Greece",
        "Argentina Vs Bosnia And Herzegovina",
        "Father's Day 2014",
        "the hole"
    ],
    "6": [
        "הונדורס",
        "ארגנטינה",
        "Argentina Vs Bosnia And Herzegovina",
        "חדשות",
        "קוסטה ריקה",
        "ערוץ 7",
        "תהילים",
        "Honduras",
        "England vs Italy",
        "חדשות 2",
        "אנגליה מול איטליה",
        "וואלה חדשות",
        "הולנד",
        "Costa Rica",
        "אורוגוואי מול קוסטה ריקה",
        "ספרד הולנד",
        "ערוץ 7",
        "גוש עציון",
        "ברזיל קרואטיה",
        "ספרד מול הולנד"
    ],
    "8": [
        "NBA",
        "Michael Schumacher",
        "ISIS",
        "Casey Kasem",
        "Germany vs Portugal",
        "ATO",
        "Majak Daw",
        "Kendall Jenner",
        "Gmail account",
        "Game Of Thrones Season 5",
        "Argentina Vs Bosnia And Herzegovina",
        "Fathers Day",
        "Father's Day 2014",
        "Switzerland vs Ecuador",
        "Le Mans",
        "France vs Honduras",
        "Us Open Golf 2014",
        "The Rock",
        "Masterchef",
        "Bbc News"
    ],
    "9": [
        "Michael Schumacher",
        "Isis",
        "Begovic",
        "Michelle Keegan",
        "Thomas Vermaelen",
        "England",
        "Honduras",
        "Ivory Coast",
        "Switzerland vs Ecuador",
        "Gary Lewin",
        "Fathers Day",
        "Casey Kasem",
        "Bbc Live",
        "Phil Neville",
        "Germany vs Portugal",
        "Ryan Gosling",
        "RIO FERDINAND",
        "MotoGP",
        "Magna Carta",
        "2018 World Cup"
    ],
    "10": [
        "Nba",
        "袁彌明",
        "德國 對 葡萄牙",
        "厄瓜多爾",
        "阿根廷 對 波士尼亞與赫塞哥維納",
        "瑞士 對 厄瓜多",
        "法國 對 宏都拉斯",
        "科特迪瓦",
        "英格蘭",
        "派路",
        "哥倫比亞",
        "天文台",
        "哥倫比亞 對 希臘",
        "父親節",
        "象牙海岸 對 日本",
        "英格蘭 對 義大利",
        "烏拉圭 對 哥斯大黎加",
        "卡斯拿斯",
        "新界東北發展計劃",
        "東北發展"
    ],
    "12": [
        "德國 對 葡萄牙",
        "馬刺",
        "阿根廷 對 波士尼亞與赫塞哥維納",
        "象牙海岸 對 日本",
        "張蒙晰",
        "法國 對 宏都拉斯",
        "世界盃足球賽 厄瓜多",
        "安以軒",
        "哥倫比亞 對 希臘",
        "英格蘭 對 義大利",
        "瑞士 對 厄瓜多",
        "烏拉圭 對 哥斯大黎加",
        "象牙海岸 對 日本",
        "阿根廷 對 波士尼亞與赫塞哥維納",
        "林百貨",
        "荷蘭",
        "夏于喬",
        "墨西哥 對 喀麥隆",
        "Nba",
        "西班牙 對 荷蘭"
    ],
    "13": [
        "Tim Duncan",
        "France vs Honduras",
        "Casey Kasem",
        "Us Open Golf 2014",
        "Switzerland Vs Ecuador",
        "MMVA 2014",
        "Kendall Jenner",
        "Bc Teachers Strike",
        "MMVA",
        "Messi",
        "NHL",
        "Ivory Coast",
        "Uruguay vs Costa Rica",
        "Colombia vs Greece",
        "Happy Fathers Day",
        "Fathers Day Quotes",
        "England vs Italy",
        "LA Kings",
        "Van Persie",
        "NBA"
    ],
    "14": [
        "результаты ЕГЭ",
        "День медика",
        "Аргентина – Босния И Герцеговина",
        "Франция – Гондурас",
        "Кот-д'ивуар – Япония",
        "Швейцария – Эквадор",
        "День отца",
        "Испания – Нидерланды Чемпионат Мира По Футболу",
        "Англия – Италия",
        "Уругвай – Коста-рика",
        "Колумбия – Греция",
        "Чили – Австралия",
        "День медика",
        "ЕГЭ",
        "День медицинского работника",
        "Шумахер",
        "футбол",
        "чемпионат",
        "Расписание Чемпионата Мира По Футболу",
        "Дженнифер Лопес"
    ],
    "15": [
        "Martin Kaymer",
        "Public Viewing",
        "Iran Gegen Nigeria",
        "Honduras",
        "Michael Schumacher",
        "ARD",
        "Deutschland Portugal",
        "Wm Ergebnisse 2014",
        "Pirlo",
        "ZDF Live Stream",
        "ZDF Livestream",
        "Wm Deutschland",
        "Düsseldorf",
        "Ribery",
        "Schweinsteiger",
        "England gegen Italien",
        "Costa Rica",
        "Benjamin Winter",
        "Ecuador",
        "Argentinien"
    ],
    "17": [
        "Schumacher",
        "Messi",
        "Wk 2014",
        "Honduras",
        "Vaderdag",
        "Engeland Italie",
        "Ecuador",
        "Pirlo",
        "ISIS",
        "Italie Engeland",
        "Kris en Lisanne",
        "Van Persie",
        "Costa Rica",
        "Uitslagen WK",
        "Chili Australie",
        "Sam Kelly",
        "Uitslagen Wk 2014",
        "Le Mans",
        "Spaanse kranten",
        "VI Oranje"
    ],
    "18": [
        "França vs Honduras",
        "Resultado Dos Jogos Da Copa",
        "Mexico",
        "Chile x Austrália",
        "México x Camarões",
        "Tabela Da Copa 2014",
        "Jogos Da Copa 2014",
        "Inglaterra Vs Itália",
        "Uruguai Vs Costa Rica",
        "Costa do Marfim vs Japão",
        "Colômbia vs Grécia",
        "Santo Antonio",
        "Copa Do Mundo Espanha",
        "Jogos Copa",
        "jogos da Copa",
        "Xabi Alonso",
        "Bruna Marquezine",
        "Sexta Feira 13",
        "Diego Costa",
        "Copa Do Mundo México"
    ],
    "19": [
        "Swiss vs Ekuador",
        "Prediksi Argentina vs Bosnia",
        "Jerman vs Portugal",
        "Prediksi Prancis vs Honduras",
        "Italy Vs England",
        "Debat Capres",
        "Kolombia vs Yunani",
        "Inggris vs Italia",
        "Meksiko Vs Kamerun Piala Dunia",
        "Uruguay vs Kosta Rika",
        "Prediksi Pantai Gading vs Jepang",
        "Obor Rakyat",
        "Jadwal Piala Dunia 2014 Brasil",
        "Belanda Spanyol",
        "Spanyol vs Belanda",
        "Prediksi Spanyol vs Belanda",
        "Hasil Pertandingan Piala Dunia",
        "Chile vs Australia",
        "Hasil UN SMP 2014",
        "Prediksi Skor Spanyol Vs Belanda"
    ],
    "21": [
        "Inglaterra Contra Italia",
        "Dia Del Padre",
        "Balotelli",
        "Feliz Dia Papa",
        "Uruguay Vs Costa Rica",
        "Inglaterra vs Italia",
        "Colombia Vs. Grecia",
        "Partido En Vivo",
        "Costa De Marfil Vs. Japón",
        "Calendario Mundial 2014",
        "Inglaterra",
        "Feliz dia del padre",
        "Imagenes Del Dia Del Padre",
        "Frases Para El Dia Del Padre",
        "Juegos Del Mundial 2014",
        "marca",
        "Andrea Pirlo",
        "Wayne Rooney",
        "Argentina Vs. Bosnia",
        "Brasil Contra México"
    ],
    "23": [
        "코트디부아르 vs 일본",
        "로또602",
        "잉글랜드 VS 이탈리아",
        "스페인 vs 네덜란드",
        "월드컵",
        "월드컵일정",
        "인간중독",
        "류현진",
        "브라질 vs 크로아티아",
        "문창극",
        "이태임",
        "신소율",
        "문창극",
        "행오버",
        "류현경",
        "로또601",
        "류현진",
        "전효성",
        "현아",
        "지방 선거 개표 결과"
    ],
    "24": [
        "Babalar Günü",
        "Fildişi S. - Japonya",
        "Fatih Harbiye Son bölüm izle",
        "Şili - Avustralya",
        "Uruguay - Kosta Rika",
        "Robben",
        "Kolombiya - Yunanistan",
        "Medcezir sezon finali",
        "Ehliyet sınav soruları",
        "Karagül Sezon Finali",
        "Işıl Karpuzoğlu",
        "İspanya Hollanda",
        "Meksika - Kamerun Dünya Kupası",
        "İngiltere İtalya",
        "TRT1 izle",
        "LYS",
        "Şeyda Coşkun",
        "Canlı maç izle",
        "Kurtlar Vadisi Pusu Son Bölüm Full izle",
        "Kardeş Payı 15.Bölüm"
    ],
    "25": [
        "Quotes About Father",
        "Côte D Ivoire Vs Japan",
        "World Cup 2014",
        "Father S Day 2014",
        "England vs Italy",
        "Happy Fathers Day",
        "Chile vs Australia",
        "Uruguay Vs Costa Rica",
        "Colombia vs Greece",
        "Happy Father S Day 2014",
        "Father S Day Message For Husband",
        "Fathers Day",
        "Spain vs Netherlands",
        "Happy Fathers Day",
        "Fathers Day Quotes",
        "Mexico vs Cameroon",
        "Enzo Pastor",
        "Sylvester Stallone",
        "Kawhi Leonard",
        "What Is Communication"
    ],
    "26": [
        "Costa De Marfil Contra Japón",
        "Andrea Pirlo",
        "Sterling",
        "Tamara Falco",
        "Pedro Zerolo",
        "Balotelli",
        "Dauphine Libere",
        "Inglaterra Contra Italia",
        "Uruguay Contra Costa Rica",
        "Colombia Contra Grecia",
        "Casillas",
        "Resultados Mundial 2014",
        "El hombre de las sombras",
        "Moto GP",
        "Sergio Ramos",
        "partidos de hoy",
        "Ole",
        "Chile contra Australia",
        "España Holanda",
        "México contra Camerún"
    ],
    "27": [
        "Paletta",
        "Mondiali Italia",
        "Darmian",
        "Italia – Costa Rica",
        "Pirlo",
        "Sturridge",
        "Andrea Pirlo",
        "Mario Balotelli",
        "Manaus",
        "Rooney",
        "Verratti",
        "Parolo",
        "Prandelli",
        "Fanny Neguesha",
        "Parolo",
        "Prossima Partita Italia 2014",
        "Carrefour",
        "Mcdonald",
        "Francia – Honduras",
        "Gabriel Paletta"
    ],
    "28": [
        "Thụy Sĩ Đấu Với Ecuador",
        "Anh Italia",
        "Argentina Đấu Với Bosnia Và Herzegovina",
        "Pháp Đấu Với Honduras",
        "Đức Đấu Với Bồ Đào Nha",
        "Chung Ket Guong Mat Than Quen 2014",
        "Uruguay vs Costa Rica",
        "Colombia Đấu Với Hy Lạp",
        "điểm thi tốt nghiệp THPT năm 2014",
        "Bờ Biển Ngà Đấu Với Nhật Bản",
        "Chile Đấu Với Úc",
        "Anh Đấu Với Ý",
        "Ngày Của Cha",
        "Ca Do Bong Da",
        "Ket Qua World Cup",
        "Tây Ban Nha Đấu Với Hà Lan",
        "Ket Qua Bong Da World Cup 2014",
        "Xem Bong Da Truc Tuyen",
        "Le Khai Mac World Cup 2014",
        "điểm thi tốt nghiệp 2014"
    ],
    "29": [
        "إنجلترا ضد إيطاليا",
        "مباراة انجلترا وايطاليا",
        "ساحل العاج ضد اليابان",
        "اهداف هولندا واسبانيا",
        "اهداف اسبانيا وهولندا",
        "اهداف هولندا واسبانيا",
        "اسبانيا وهولندا",
        "امتحان الفيزياء للثانوية العامة 2014",
        "تشيلي ضد أستراليا",
        "اهداف كاس العالم 2014",
        "كولومبيا ضد اليونان",
        "اجابة امتحان الفيزياء 2014",
        "uruguay vs costa rica",
        "تردد قناة Bein Sport",
        "اهداف كاس العالم 2014",
        "المكسيك ضد الكاميرون كاس العالم",
        "اهداف البرازيل وكرواتيا",
        "القنوات المفتوحة الناقلة لكاس العالم 2014",
        "بين سبورت",
        "مباراة افتتاح كاس العالم 2014"
    ],
    "30": [
        "Uruguay Vs Costa Rica",
        "Inglaterra Contra Italia",
        "Costa De Marfil Vs. Japón",
        "Colombia Vs. Grecia",
        "Dia Del Padre",
        "Resultados Del Mundial 2014",
        "Frases Para El Dia Del Padre",
        "Iker Casillas",
        "Andrea Pirlo",
        "Luis Ventura",
        "Colombia",
        "Chile vs Australia",
        "España Vs. Holanda",
        "México vs Camerún",
        "España contra Países Bajos en Copa Mundial",
        "Ver Mundial Online",
        "Futbol En Vivo",
        "España contra Países Bajos",
        "Presentacion Del Mundial Brasil 2014",
        "Vicky Xipolitaki"
    ],
    "31": [
        "Wybrzeże Kości Słoniowej – Japonia",
        "Manaus",
        "Sowa i Przyjaciele",
        "Agnieszka Szczurek",
        "Szwajcaria – Ekwador",
        "Francja – Honduras",
        "Pirlo",
        "Włochy Anglia",
        "Anglia Włochy 2014",
        "Junior Diaz",
        "Bartłomiej Sienkiewicz",
        "Kostaryka",
        "Anglia – Włochy",
        "Chile – Australia",
        "Kolumbia – Grecja",
        "Wprost",
        "Mecz Hiszpania Holandia",
        "Robin van Persie",
        "Robben",
        "Joel Campbell"
    ],
    "32": [
        "Uruguay Vs Costa Rica",
        "Inglaterra vs Italia",
        "Elecciones Presidenciales Colombia 2014",
        "Costa de Marfil",
        "Copa Mundial Colombia",
        "Andrea Pirlo",
        "David Ospina",
        "Teofilo Gutierrez",
        "Chile vs Australia",
        "México vs Camerún",
        "España contra Países Bajos en Copa Mundial",
        "Seleccion Colombia",
        "Futbol En Vivo",
        "España contra Países Bajos",
        "Partidos del Mundial",
        "Cristiano Ronaldo",
        "Xabi Alonso",
        "Diego Costa",
        "Lina Luna",
        "Copa Mundial España"
    ],
    "33": [
        "ไก่ ภาษิต",
        "มวยไทย7สี",
        "อังกฤษ",
        "อังกฤษ อิตาลี",
        "สเปน ฮอลแลนด์",
        "สเปน ฮอลแลนด์",
        "ฮอลแลนด์",
        "ดูบอล",
        "ช่อง7",
        "ผลบอลโลก",
        "ช่อง5",
        "ยกเลิกเคอร์ฟิว",
        "เนย์มาร์",
        "World Cup 2014",
        "ฟุตบอลโลก",
        "ผลบอล",
        "บอลโลก",
        "บราซิล",
        "บอลโลก 2014",
        "World Cup"
    ],
    "34": [
        "Father S Day",
        "Switzerland vs Ecuador",
        "France vs Honduras",
        "Fathers Day Wishes",
        "England vs Italy",
        "Uruguay vs Costa Rica",
        "Côte D Ivoire Vs Japan",
        "Colombia vs Greece",
        "Happy Fathers Day",
        "Father S Day 2014",
        "Argentina vs Bosnia and Herzegovina",
        "Fathers Day Quotes",
        "Now You See Me",
        "Spain vs Netherlands",
        "Mexico vs Cameroon",
        "Jennifer Lopez",
        "Chile vs Australia",
        "Fabregas",
        "Messi",
        "Germany World Cup 2014 Squad"
    ],
    "35": [
        "Кот-д Ивуар – Япония",
        "Громадське",
        "Англия – Италия",
        "Ил 76",
        "Уругвай – Коста-рика",
        "Чили – Австралия",
        "Колумбия – Греция",
        "Горловка",
        "Посольство России в Киеве",
        "Испания – Нидерланды",
        "Футбол",
        "Мариуполь",
        "Чемпионат Мира По Футболу 2014 Смотреть Онлайн",
        "Чм 2014 По Футболу",
        "Іспанія – Нідерланди",
        "День медика",
        "2 2",
        "демарш",
        "Янукович",
        "пятница 13"
    ],
    "36": [
        "وزارة الصحة",
        "وزارة الصحة",
        "مباراة انجلترا وايطاليا",
        "ساحل العاج ضد اليابان",
        "مباراة ايطاليا وانجلترا",
        "ايطاليا وانجلترا",
        "كوستاريكا",
        "مباريات كاس العالم",
        "مباراة انجلترا وايطاليا",
        "ايطاليا",
        "بيرلو",
        "اهداف كاس العالم 2014",
        "England vs Italy",
        "uruguay vs costa rica",
        "إنجلترا ضد إيطاليا",
        "تشيلي ضد أستراليا",
        "كولومبيا ضد اليونان",
        "فان بيرسي",
        "اهداف هولندا واسبانيا",
        "بث مباشر مباراة اسبانيا وهولندا"
    ],
    "37": [
        "Côte D Ivoire Vs Japan",
        "Fathers Day",
        "England vs Italy",
        "Uruguay Vs Costa Rica",
        "Colombia vs Greece",
        "Chile vs Australia",
        "Spain vs Netherlands",
        "Mexico vs Cameroon",
        "Fabregas",
        "SuperSport",
        "World Cup 2014",
        "Yahoo Mail",
        "WhatsApp",
        "Yahoo",
        "Yahoo.com",
        "KRA",
        "Diego Costa",
        "Rihanna",
        "Madaraka Day",
        "Raila"
    ],
    "38": [
        "Inglaterra vs Italia",
        "Uruguay Vs Costa Rica",
        "Costa De Marfil Vs. Japón",
        "Colombia Vs. Grecia",
        "Diario Marca",
        "Chile vs Australia",
        "México vs Camerún",
        "España Vs. Holanda",
        "España contra Países Bajos en Copa Mundial",
        "España Contra Países Bajos",
        "marca",
        "Mourinho",
        "Jean Beausejour",
        "Cristiano Ronaldo",
        "Copa del Mundo 2014",
        "Brasil contra Croacia",
        "FIFA",
        "Mundial Brasil 2014",
        "Canal 13",
        "Claudia Leitte"
    ],
    "39": [
        "England vs Italy",
        "Franța Vs. Honduras",
        "Uruguay Vs. Costa Rica",
        "Chile vs. Australia",
        "Van Persie",
        "Mexic Vs. Camerun",
        "Cm 2014",
        "Claudia Leitte",
        "World Cup 2014",
        "Jennifer Lopez",
        "Google Space",
        "Rafael Nadal",
        "Selena",
        "Nigeria",
        "Simona Halep",
        "Eurosport Live",
        "Roland Garros Live",
        "Formula 1",
        "Enrique Iglesias",
        "Roland Garros"
    ],
    "40": [
        "Father S Day 2014",
        "Côte D Ivoire Vs Japan",
        "Fathersday",
        "Happy Fathers Day",
        "England vs Italy",
        "Uruguay vs Costa Rica",
        "Chile vs Australia",
        "Fathers Day Quotes",
        "Colombia vs Greece",
        "Spain vs Netherlands",
        "Mexico vs Cameroon",
        "SuperSport",
        "Friday the 13th",
        "Kefee",
        "World Cup 2014",
        "Jennifer Lopez",
        "Eskom",
        "World Cup 2014 Fixtures",
        "Cesc Fabregas",
        "World Cup 2014 Schedule"
    ],
    "41": [
        "Côte D Ivoire – Japon",
        "Engeland versus Italië",
        "Resultat Coupe Du Monde 2014",
        "Pirlo",
        "Angleterre Italie",
        "Uruguay Costa Rica",
        "Colombie – Grèce",
        "24H du Mans",
        "Espagne Pays-bas",
        "Wk 2014",
        "Chili Australie",
        "Sporza",
        "Mexique Cameroun",
        "Robben",
        "Spanje Versus Nederland",
        "Fifa Wereldkampioenschap Voetbal",
        "Diego Costa",
        "Jessica Rabbit",
        "Marcelo",
        "Ronaldo"
    ],
    "42": [
        "Balotelli",
        "England Italien",
        "Pirlo",
        "Costa Rica",
        "Chile mot Australien",
        "England Mot Italien",
        "Dreamhack",
        "Anna Faith Carlson",
        "Colombia",
        "Mexiko Mot Kamerun",
        "Vätternrundan",
        "One Direction",
        "Van Persie",
        "Spanien Nederländerna Vm",
        "Vm Fotboll 2014",
        "Summerburst",
        "Kartellen",
        "Radiotjänst",
        "Diego Costa",
        "Holland"
    ],
    "43": [
        "Anglie – Itálie",
        "Uruguay – Kostarika",
        "Pražská muzejní noc",
        "Mexiko – Kamerun",
        "Daniel Landa",
        "Votvirak",
        "Mistrovství Světa Ve Fotbale 2014",
        "Brazílie – Chorvatsko",
        "Neymar",
        "Čt Sport",
        "Lucie",
        "Jiří Bruder",
        "GE Money Bank",
        "Jaroslav Kaňkovský",
        "Rihanna",
        "Justin Timberlake",
        "iOS 8",
        "Mezinárodní den dětí",
        "zemětřesení",
        "Gambrinus liga"
    ],
    "44": [
        "Andrea Pirlo",
        "Schweiz gegen Ecuador",
        "Frankreich gegen Honduras",
        "Manaus",
        "Buffon",
        "MotoGP",
        "Uruguay gegen Costa Rica",
        "England gegen Italien",
        "Kolumbien gegen Griechenland",
        "Le Mans 2014",
        "Elfenbeinküste gegen Japan",
        "Iker Casillas",
        "Regenbogenparade Wien 2014",
        "Benjamin Winter",
        "Regenbogenparade",
        "Chile Australien",
        "Grazathlon",
        "Diego Forlan",
        "Xabi Alonso",
        "Sergio Ramos"
    ],
    "45": [
        "Elefántcsontpart -- Japán",
        "Franciaország -- Honduras",
        "Svájc -- Ecuador",
        "Uruguay -- Costa Rica",
        "Anglia -- Olaszország",
        "Chile -- Ausztrália",
        "Kolumbia -- Görögország",
        "Robben",
        "van Persie",
        "Spanyolország -- Hollandia Világbajnokság",
        "Grosics Gyula",
        "Mexikó -- Kamerun",
        "Péntek 13",
        "Brazil Horvát",
        "Világbajnokság 2014",
        "Foci Vb 2014",
        "Brazília -- Horvátország",
        "Brazília Horvátország",
        "világbajnokság",
        "Foci Vb"
    ],
    "46": [
        "Angleterre Italie",
        "Côte D Ivoire – Japon",
        "Wayne Rooney",
        "Pirlo",
        "Andrea Pirlo",
        "Benjamin Winter",
        "Suisse – Équateur",
        "Frankreich gegen Honduras",
        "Sterling",
        "Joel Campbell",
        "Argovia Fest",
        "Uruguay gegen Costa Rica",
        "England gegen Italien",
        "Elfenbeinküste gegen Japan",
        "Kolumbien gegen Griechenland",
        "Chili Australie",
        "Schweiz Gegen Ecuador",
        "Tour de Suisse",
        "Buffon",
        "Le Mans 2014"
    ],
    "47": [
        "Costa do Marfim vs Japão",
        "Inés Sainz",
        "Uruguai Vs Costa Rica",
        "Colômbia vs Grécia",
        "Casillas",
        "Espanha Holanda 2014",
        "Espanha Vs Holanda Copa Do Mundo",
        "Inglaterra Vs Itália",
        "México Vs Camarões",
        "rtp",
        "as",
        "Diego Costa",
        "The Libertines",
        "Abertura Da Copa 2014",
        "Campeonato Do Mundo 2014",
        "Neymar",
        "Brasil Croacia",
        "Mundial",
        "Claudia Leitte",
        "Andressa Urach"
    ],
    "48": [
        "Κοστα Ρικα",
        "Γιορτη Του Πατερα",
        "Αγγλια Ιταλια",
        "Ελλαδα Κολομβια Μουντιαλ",
        "Ακτη Ελεφαντοστου",
        "Κολομβία Εναντίον Ελλάδα",
        "Ουρουγουάη Εναντίον Κόστα Ρίκα",
        "Ισπανια Ολλανδια",
        "Παγκόσμιο Κύπελλο Ελλάδα",
        "Εθνικη Ελλαδοσ",
        "Παγκόσμιο Κύπελλο Κολομβία",
        "Χιλη Αυστραλια",
        "Καρνεζησ",
        "Ισπανία Ολλανδία Παγκόσμιο Κύπελλο",
        "Άρης Σταθάκης",
        "Παγκόσμιο Κύπελλο Βραζιλία",
        "FIFA",
        "Nerit",
        "Mundial 2014",
        "Mundial"
    ],
    "49": [
        "Pirlo",
        "Le Mans 2014",
        "Costa Rica",
        "LeMans 2014",
        "Titanic",
        "Lemans",
        "Lana Del Rey",
        "Diego Costa",
        "Vm 2014",
        "Northside",
        "Ronaldinho",
        "Vm Manager",
        "Jennifer Lopez",
        "Neymar",
        "Tv2 Play",
        "World Cup 2014",
        "Hulk",
        "Messi",
        "VM",
        "Ronaldo"
    ],
    "50": [
        "Costa Rica",
        "Alexander Stubb",
        "Chile vs. Australia",
        "NHL",
        "ZZ Top",
        "Espanja Vs. Alankomaat",
        "Claudia Leitte",
        "Stockmann",
        "Meksiko Vs. Kamerun",
        "Jessica Rabbit",
        "Ronaldo",
        "Hulk",
        "Messi",
        "Jennifer Lopez",
        "Neymar",
        "Brasilia",
        "Jao",
        "Slenderman",
        "AKT",
        "NHL"
    ],
    "51": [
        "Pirlo",
        "John Mayer",
        "Costa Rica",
        "Nordsjørittet",
        "Nordsjørittet 2014",
        "Spania Nederland Vm",
        "Vm Fotball",
        "Færderseilasen",
        "Lana Del Rey",
        "Marcelo",
        "fotball-VM 2014",
        "Vm 2014",
        "Fotball Vm",
        "Neymar",
        "Vm Fotball 2014",
        "Brasil",
        "Dealextreme",
        "Rik Mayall",
        "Stefan Strandberg",
        "E3"
    ],
    "52": [
        "Côte D Ivoire Vs Japan",
        "England vs Italy",
        "Uruguay Vs Costa Rica",
        "Colombia vs Greece",
        "Kefee",
        "Spain vs Netherlands",
        "Chile vs Australia",
        "What Is Settlement",
        "Fabregas",
        "Mexico vs Cameroon",
        "World Cup 2014",
        "World Cup fixtures",
        "Rik Mayall",
        "new Emir of Kano",
        "Dora Akunyili",
        "Nigeria vs USA",
        "Ado Bayero",
        "Nigeria vs Greece",
        "Maya Angelou",
        "Nigeria vs Scotland"
    ]
}
EOL;

echo $data;
?>